#include <avr/io.h>

#include <stdint.h>
#include <stddef.h>

#define ZRTOS_ARCH__ATMEGA328P
#define ZRTOS_BOARD__AVR_SOFTWARE_EMULATOR

#include <zrtos/error.h>
#include <zrtos/types.h>
#include <zrtos/malloc.h>

ZRTOS_MALLOC__GLOBAL_HEAP(heap,500);

#include <zrtos/cbuffer.h>

typedef enum{
	ZRTOS_VFS_MODULE_MAX7219_OPCODE__NOOP         = 0
	,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_0      = 1
	,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_1      = 2
	,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_2      = 3
	,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_3      = 4
	,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_4      = 5
	,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_5      = 6
	,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_6      = 7
	,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_7      = 8
	,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DECODE_MODE  = 9
	,ZRTOS_VFS_MODULE_MAX7219_OPCODE__INTENSITY    = 10
	,ZRTOS_VFS_MODULE_MAX7219_OPCODE__SCAN_LIMIT   = 11
	,ZRTOS_VFS_MODULE_MAX7219_OPCODE__SHUTDOWN     = 12
	,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DISPLAY_TEST = 15
}zrtos_vfs_module_max7219_opcode_t;

int main(void){
	ZRTOS_MALLOC__GLOBAL_HEAP_INIT(heap);
	uint8_t arr[] = {
		1
		,2
		,3
		,4
		,5
		,6
		,7
		,8
		,9
		,10
		,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_0
		,0x0
		,2
		,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_1
		,0x0
		,2
		,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_2
		,0x0
		,2
		,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_3
		,0x0
		,2
		,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_4
		,0x0
		,2
		,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_5
		,0x0
		,2
		,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_6
		,0x0
		,2
		,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_7
		,0x0
		,2
		,ZRTOS_VFS_MODULE_MAX7219_OPCODE__SHUTDOWN
		,1
		,2
		,ZRTOS_VFS_MODULE_MAX7219_OPCODE__DIGIT_0
		,0x8
	};
	zrtos_cbuffer_t buffer;
	size_t outlen;
	zrtos_cbuffer__init(&buffer);

	zrtos_cbuffer__put_ex(
		 &buffer
		,1
		,&outlen
		,arr
		,sizeof(arr)/sizeof(arr[0])
	);

	return 0;

}

