/*
 * Copyright (c) 2024 ykat UG (haftungsbeschraenkt) - All Rights Reserved
 *
 * Permission for non-commercial use is hereby granted,
 * free of charge, without warranty of any kind.
 */
#ifndef ZRTOS_CFG_H
#define ZRTOS_CFG_H
#ifdef __cplusplus
extern "C" {
#endif


/**
 * @file
 * 
 * Autogenerated file containing list of possible config option.
 */
#define ZRTOS_DEBUG__CFG_ENABLED
#define ZRTOS_DEBUG__CFG_MEMORY_CONSOLE
#define ZRTOS_EVENT_INDEX__CFG_ENABLE_PROGMEM
#define ZRTOS_MALLOC__CFG_DISABLE_FREE
#define ZRTOS_PROGMEM__CFG_ENABLED
#define ZRTOS_VHEAP_TASK_SCHEDULER__CFG_ENABLED


#ifdef __cplusplus
}
#endif
#endif
