/*
 * Copyright (c) 2024 ykat UG (haftungsbeschraenkt) - All Rights Reserved
 *
 * Permission for non-commercial use is hereby granted,
 * free of charge, without warranty of any kind.
 */
#ifndef ZRTOS_CFG_H
#define ZRTOS_CFG_H
#ifdef __cplusplus
extern "C" {
#endif


/**
 * @file
 * 
 * Autogenerated file containing list of possible config option.
 */
#define ZRTOS_CBUFFER__CFG_DATA_LENGTH
#define ZRTOS_DEBUG__CFG_ENABLED
#define ZRTOS_DEBUG__CFG_MEMORY_CONSOLE
#define ZRTOS_EVENT_INDEX__CFG_ENABLE_PROGMEM
#define ZRTOS_MALLOC__CFG_DISABLE_FREE
#define ZRTOS_PROGMEM__CFG_ENABLED
#define ZRTOS_STR__CFG_DTOA_PRECISION
#define ZRTOS_VFS_FILE_DESCRIPTOR__CFG_MAX
#define ZRTOS_VFS_MODULE_AVR_ADC__CFG_MAX_CHANNEL
#define ZRTOS_VFS_MODULE_AVR_ADC__CFG_PRESCALER
#define ZRTOS_VFS_MODULE_AVR_ADC__CFG_REFERENCE_VOLT
#define ZRTOS_VFS_MODULE_AVR_ADC__CFG_VREF
#define ZRTOS_VFS_MODULE_SPI__CFG_DATA_LENGTH
#define ZRTOS_VFS_MODULE_SPI__CFG_TRANSFER_LENGTH
#define ZRTOS_VFS_PLUGIN__CFG_USE_SWITCH
#define ZRTOS_VHEAP_TASK_SCHEDULER__CFG_ENABLED
#define ZRTOS_VM_FUNCTION_INDEX__CFG_ENABLE_PROGMEM


#ifdef __cplusplus
}
#endif
#endif
